### ISSUE TITLE
tp link archer ax 

### ISSUE THREAD

**Issue by L1ttleWizard** [wlp5s0/ro#1]
Можно-ли юзать tp link ax серии, там полюбому придется накатывать openwrt, но я точно не знаю, что там юзается, и есть-ли это на новых tp-linkax

**Comment by wlp5s0** [comment]
привет. сложно сказать в общем, нужно смотреть на сайте OpenWRT для конкретной модели. Если на неё накатывается OpenWRT, то я смогу собрать нужную прошивку. Если нет - либо опустить руки, либо ради прикола написать в техподдержку TP-Link. Один фиг на новые роутеры wpad встанет без проблем.

**Comment by L1ttleWizard** [comment]
Мб что-то гигабитное порекомендуешь, охота сделать ftp

**Comment by wlp5s0** [comment]
делать ftp на роутере? уфф
Можно очень быстро упереться в производительность процессора. Я пробовал сделать шару с внешним жестким диском на tl-mr3020 под owrt, скорость была в разы меньше, чем мог выдать жесткий.
Я бы взял с китая дешевую железку форм-фактора intel nuc или даже попробовал зашить под armbian приставки вроде selenga r1 (x96q с али), и делал на них. Ну, или сделать сразу нормальный nas за те же деньги в форм-факторе ПК.
А сеть уже да, поднимать на роутере с гиговым коммутатором и 5 ГГц. Вроде как поддерживается TP-Link Archer A6 - но тут не могу знать, поскольку не видел глазами, какие ревизии их продаются у нас в розницу. Ну или xiaomi mi router 4a Giga edititon, но их, как и любые xiaomi, шить через пень-колоду- openwrt invasion
короче, честно? делай nas на внешней железке и гиговом коммутаторе на 5 портов от условных тех же tp-link, а общажную сеть оставь на том зоопарке железа, которое там уже есть. вот так вот как-то

**Comment by L1ttleWizard** [comment]
Принял, спасибо, пока возьму скорее всего  A6, хотя и жаль, что почти все новые ax роутеры tp-link (за более менее адекватные бабки) не дружат с owrt

**Comment by wlp5s0** [comment]
Пиши в тг wlp5s0, глянем, может соберу под него прошивку в свободное время.
